<h1 id="Week3">Week 3. Functions,Slicing Data Structures, and More Numpy.</h1>

Today we will continue learning Python by learning how to make a function–both in a notebook and in a separate .py script file. We will also learn more about slicing arrays, lists, and tuples and using Numpy in general.


## Functions.

### Functions are a collection of statements that:
- take some input from the code
- do something/ perform a computation
- might return some output to the main code.

 $ z = f(x,y)$ ->
`return_values(s) = f(argument(s)`

- *When do I make a function?* Do you need to do this calculation more than once in the future? 

- To call them you need to use: my_function_name( 

- You may here functions and methods used interchangably. After we get into object-oriented programming the term *method* will make more sense. For now, just think of a *method* as a synonym of *function*.

In [ ]:
print( " Hello World! " )  #---> you call the function print() and it is 
                           #---> tasked to print the text between the quotes

In [55]:
# some other build-in function you may see:

my_int = int( 3.1 )      # ----> get the 3.1 and give me the integer
print(my_int)

3


### Python has many *modules*. *Modules* are collections or libraries of functions. To call them you first need to import them:

- `import module_name`
- or to abbreviate the module name: `import module_name as module_shortname`
- this is dangerous because you might shadow other functions with the same name from a different module: `from module_name import *`. It imports *all* of the functions in the module without the module name.
- we can also import a single function or subset of functions using: `from module_name import function_name`



## How you call a function from the module changes depending on how you import the module:

### 1. When you use:
`import module_name`

### you need to call a function as:
`module_name.function_name()`


**Try it!** import the math module and round the number 4.7 down and up using functions.

In [1]:
# ---> Note that int() is not a rounding function; for that you have the floor() and ceil() in math:

import math

In [2]:
#round down and up:
math.floor( 4.7 ) , math.ceil( 4.7 )

(4, 5)

### 2. For most modules it is common practice to import them following this example:

In [61]:
import numpy as np  #--> this tells Python to import the module numpy under the name np 
                    #    this simplifies your coding as instead of writing numpy.blabla() 
                    #    you just need to write np.blabla()
                    #--> may not look as much gain with numpy but think of: import matplotlib.pyplot as plt 

In [65]:
#import the numpy module with the short name 'np' and round the number 3.2 down, up,
#and following the standard rounding rule using numpy functions.
np.floor( 3.2 ), np.ceil(3.2), np.round(3.2)

(3.0, 4.0, 3.0)

**Tip:** The numpy module contains everything you would need from the math module and more. If you are importing *numpy*, you do not need to also import *math*. 

### 3. If you want to avoid using the math.* ,np.* etc you may also chose to change the import command to:
`from module_name import *`
    
### Then you call a function as:
`function_name()`

In [69]:
from math import *   # --> this goes into math and imports all functions with their name  
                     # --> ( so you don't need a math.* )

In [7]:
print( floor( 4.7 ) , ceil ( 4.7 )  )

4 5


**WARNING!** This is not a good practice generally, as more than one packages may share the same name of a function; you want to separate them and know what package you call (e.g., np.pi or math.pi....)

In [66]:
print( np.pi, pi)

3.141592653589793 3.1415


### Practice:
Now that you imported numpy use functions: 
- use array() to make a numpy array called `test1` with the numbers `[ 1, 2, 5, 3]`.
- Call functions `max()`, `min()` to calculate the max and min of the array.
- Determine what the functions `argmin()` and `argmax` do.
- Find the mean of test1

### Building Functions.
Sometimes you have a task that you need to do over and over and it takes a while to write the code. Functions allow you to call a sequence of code over again.

### To make your own function you need the following structure:

    def function_name( argument(s) ) : 

          """
          This is called a docstring. It is instantiated with 3 quotes (""") It is essentially a comment where    
          useful notes go about input/output and what function desscription goes.
          
          Input: argument1 - this is ...    
          Output: return_value1 - this is ...
          
          All built-in Python functions have docstrings. To view a functions docstring type
          help(function_name(arguments)) or SHIFT + TAB where the cursor is in the () following
          the function_name.
          """    
        
          **this is where all my code goes** 
        
          return return_value(s)

**WARNING!** If you don't indent you code for defining function, you will get an **IndentationError**.

### Practice:
Make a function `position_car_v` that calculates the position of a car with initial position `x0`, moving with constant velocity `v0` for time `t`. Where all quantities are in SI base units. The function should also print an informative statement about the car's position

- Discuss: what should the input of the function be?
- what should the output be?
- what should a good docstring include?

Now let's call our function for an initial position of $x_0 = -2100 ~\mathrm{m}$, $v_0 = 200 ~\mathrm{\frac{m}{s}}$ and $t = 10 ~\mathrm{s}$. Print the result.

In [21]:
vel = 200
time  = 10 
pos0 = -2100

### Docstrings
Why is a good and informative docstring important? Imagine calling the docstring from above and just getting a ""Function that calculates the position of the car in [m] traveled by object moving with constant velocity in [ m/s] over time [s]"". What could go wrong? Input order matters!

### Keyword Arguments:
To make sure the user inputs the right variables you can use keyword arguments (KWARGS). You can also set default values in case the user doesn't input it. 

- Write another function `position_car_a` that calculates the 1d position of the car with constant acceleration. Use KWARGS and set the default value of x0 to 0.
- Call it for $a = -9.8 \mathrm{\frac{m}{s^2}}$, $v_0 = 11 \mathrm{\frac{m}{s}}$, and $t = 1 ~\mathrm{s}$.
- Print the docstring to the screen.

In [1]:
distance = position_car_a(a= -9.8, v0 = 11, t = 1)
print('The (very fast) car is',distance,'m from the origin.')

NameError: name 'position_car_a' is not defined

In [26]:
help(position_car_a)

Help on function position_car_a in module __main__:

position_car_a(t=None, v0=None, a=None, x0=0)
    Function that calculates the 1D position of a car with initial position x0, constant velocity, v0, 
    and for time, t. All quantities should be in SI base units.
    Follows xf = x0 + v0 * t + 0.5*a*t**2, assuming constant speed. 
    Input: 
        x0 - initial position [m] (Default value is 0)
        v0 - initial velocity[ m/s]
        a  - constant acceleration
        t  - time interval [ s ]
    Output: position [ m ]



### .py files
When writing a function, think if you may use it in the future possibly in another notebook. If so, write it on a separate .py file. You can then import it in whichever code you are working in the future just like you do with numpy.


### Practice:
Create a function called `F2C` in a .py file called `my_functions.py`. 
1. From your Jupyter dashboard choose "New" from the right side of the screen.
2. Choose "New File"
3. Change the filename from "untitled1.py" to "my_functions.py"
4. Write your script. 

#### Let's import F2C and run it:
- Call the docstring to figure out what distance 2 does.
- Call the function for `degF = 98.6`. 

In [115]:
import my_functions as myf

In [103]:
myf.F2C?

Signature: myf.F2C(degF)
Docstring:
Converts degrees in F to degrees in C.
Input: temp. in degrees F.
Output: temp. in degrees C.
File:      ~/Documents/GitHub/phz3150/2025 lectures/my_functions.py
Type:      function

In [27]:
print(myf.F2C(98.6))


37.0


## Nested functions.

### Practice:

Write another function `F2K` in your .py file that converts from $^\circ$F to Kelvin where 0 K is -273.15 $^\circ$C and one unit K is equal to a change of 1 $^\circ$C. Use F2C in your code. 

### Importing multiple functions from a .py file.
You can import multiple functions the same way as we would from a module.

`import my_functions as myf`

or 

`from my functions import *`

or 

`import my_functions`

Restart your Python kernel, import my_functions and call `F2K` to convert the average temperature on Saturn's moon Titan (-290 $^\circ$F) to Kelvin.

In [28]:
import my_functions as myf

Titan_temp_K = myf.F2K(-290)

print("The average temperature on Saturn's moon Titan is", Titan_temp_K, "K.")

The average temperature on Saturn's moon Titan is 94.26111111111109 K.


Let's do our imports again since we restarted our Python kernels.

In [29]:
import numpy as np
import matplotlib.pyplot as plt

### Practice: 

Stars are far away from us. So far away that it is hard to describe using normal distance units. The units to describe distances are light years (ly) or parsecs (pc). A parsec is $\sim 3.262$ ly. Knowing that 1 pc = $1.9174 \times 10^13$ miles make a function pc_to_mi that takes as input the name of the star and its distance from us in pc, prints an informative statement of how far the star is in miles, and returns nothing. Run it for Betlegeuse ($\sim$168 pc) and Arcturus ($\sim$11pc).


## Local variables and global variables

A function has its own memory block that is reserved for variables created within that function. This block of memory is not shared with the whole notebook memory block. Therefore, a variable with a given name can be assigned within a fucntion without changing a variable with the same name outside of the function. The memory block associated with the function is opened every time a function is used.

### Practice:

Create a function `grav` that takes two masses `m_A` and `m_B` and a distance between their centers `r` and returns the force of the gravitational force of one mass on the other following:

$|\vec{F}_{A,B}| = \frac{Gm_Am_B}{r^2}$
        
where $G = 6.67 \times 10^{-11} \mathrm{Nm^2/kg^2}$.

- Call it for $m_A = 5.97 \times 10^24$ kg (Earth) and $m_B = 1.00$ kg at a distance of Earth's radius: r = $6.37 \times 10^6$ m.
- Print the variable $G$.

In [118]:
print(grav(5.97e24,1,6.37e6))

9.813440652193735


`print(G)` returns an error that G is not defined!
G is a *local* variable, only accessable by the function *grav*.

If we want the variable $G$ to be accessable everyone, we use the keyword global to let Python know this variable is a ***global*** variable that it can be used both outside and inside the function.

**EXAMPLE:** Define $G$ as the global variable, and then use and change the value $G$ within the function, *grav*.

In [121]:
G = 0

def grav(m_A,m_B,r):
    """
    Calculates the magnitude of the gravitational force between masses m_A and m_B.
    All quantities are in base SI units.
    Input:
    m_A - mass in kg
    m_B - mass in kg
    r - distance between masses' centers in m.
    Output:
    Force in N.
    """
    global G
    G = 6.67e-11 #Nm^2/kg^2

    F = G*m_A*m_B/r**2

    return F

In [123]:
print(G)
print(grav(5.97e24,1,6.37e6))
print(G)

0
9.813440652193735
6.67e-11


### Lambda Functions
Sometimes, we don't want to use the normal way to define a function, especially if our function is just one line. In this case, we can use anonymous function in Python, which is a function that is defined without a name. This type of functions also called a **$\lambda$ function**, since they are defined using the *lambda* keyword. A typical lambda function is defined:

```python
lambda arguments: expression
```

It can have any number of arguments, but with only one expression. 

**TRY IT!** Define a labmda function, which square the in put number. And call the function with input 2 and 5. 

In [129]:
square = lambda x: x**2

print(square(2))
print(square(3))
print(square(2) + square(4) + square(6))

4
9
56


## Slicing Data Structures in Python

As we mentioned last week, sometimes we have a lot of data in a list, tuple, string, or numpy array but we only want to access some of it. We can then use slicing to get a part of our list/tuple/numpy array/ pandas dataframe etc....

To slice something we need to use brackets  [   ] and we need to know the dimensions of our data. In the simple 1D case we use

The numbers in the brackets represent an address (index/indices) in the array, list, tuple, etc. Python *always* starts counting with $i = 0$. We usually label indices abstractly in Latin as $i, j, k,$ ... or sometimes in Relativity in Greek $\mu, \nu, \rho,$ .... 

The value stored at the address of the $i^{th}$ row and $j^{th}$ column in the matrix $ M $ is denoted $M_{i,j}$ 

**TRY IT!** Create a 2D $3 \times 3$ array with the numbers 0 - 8 ordered left-to-right and top-to-bottom. Slice out the value 5 using array slicing.

In [19]:
test_slicing_2d = np.arange( 9 )
test_slicing_2d = np.reshape(test_slicing_2d, (3,3))

#check your array:
print(test_slicing_2d)
print(test_slicing_2d[1,2])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
5


### Slicing a subarray 1D.

To slice a subarray from a 1 dimensional data structure use the following format:

`My_1D_array[Start_index: End_but_NOT_INCLUDING_index : With_step_size_of]`

**Try it!**

In [42]:
#create a 1D array with 17 evenly-spaced elements starting on 2 and ending on 10:

My_1D_array = np.linspace(2,10,num = 17)  

print(My_1D_array)

#slice out the numbers 4.5 - 7 from the array:

My_slice = My_1D_array[5:11]

print(My_slice)

[ 2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5  8.   8.5
  9.   9.5 10. ]
[4.5 5.  5.5 6.  6.5 7. ]


**WARNING:** python (like most programming languages) starts counting arrays at 0 ( so first element of array x is x[ 0 ] )! Also, it is easy to forget the Python requires the end index to be greater than the last index included. (considers the open set)

### Practice:

Create a slice `My_other_slice` which contains the number at every *odd* index of `My_1d_array` listed backwards and starting with the number 7.5. Print it.

For n-dimensional arrays you can use the same slicing rules for each dimension separated by commas.

### Practice:

Create a $4 \times 4$ array `array4` that contains evenly spaced numbers from 1 to 4 ordered from left-to-right and top-to-bottom. Print a slice containing the subarray: 

$\begin{pmatrix} 
2.8 & 3.0 \\
3.6 & 3.8 \\
\end{pmatrix}$



### Appending lists or numpy arrays:

Numpy arrays: use the function `np.append(my_array, values_to_append_to_end)`

Lists: use the list method append. If the list is *my_list*: `my_list.append(values_to_append_to_end)`

**Try it!**

In [14]:
#Numpy array:
array = np.arange(10)
array = np.append(array,11)
array = np.append(array,[10,9,8,7,6])
print(array)

#List:
my_list = [1,2,'red','blue']
my_list.append('fish')
print(my_list)

[ 0  1  2  3  4  5  6  7  8  9 11 10  9  8  7  6]
[1, 2, 'red', 'blue', 'fish']


**TRY IT!**
Sort the array and put it in reverse order:

In [15]:
array = np.sort(array)
array = np.flip(array)
print(array)

[11 10  9  9  8  8  7  7  6  6  5  4  3  2  1  0]


**TRY IT!** Extend `my_list` by appending the list `['bird','frog','dog']` on to the end.

In [16]:
my_list.append(['bird','frog','dog'])
print(my_list)

[1, 2, 'red', 'blue', 'fish', ['bird', 'frog', 'dog']]


Oops! I added a list to the list! I should use *extend* to append just the elements of the list.

In [17]:
my_list = my_list[0:-1]
my_list.extend(['bird','frog','dog'])
print(my_list)

[1, 2, 'red', 'blue', 'fish', 'bird', 'frog', 'dog']


In [19]:
my_list.remove('fish')   # remove the "4" from the list

ValueError: list.remove(x): x not in list

In [20]:
print(my_list)

[1, 2, 'red', 'blue', 'bird', 'frog', 'dog']


### Practice:

Create a list `count` that contains the numbers from 10 - 20. Create a np.array `count_a` from `count`. Create a tuple `count_t` from `count`. Change the last element of each to 0. Does it work for all of them? Why or why not?

`count_t[-1] = 0` Doesn't work since tuples are immutable!

#### A clever work around?
- First let's check where count_t is in memory:

In [96]:
print( id( count_t ) )

4533795648


In [98]:
count_t = count_t[0:9]+(0,)

In [99]:
print(count_t,type(count_t))
print(id(count_t))

(10, 11, 12, 13, 14, 15, 16, 17, 18, 0) <class 'tuple'>
4533885888


Notice that we simply *shadowed* `count_t` with a tuple having the same name. The memory address has changed. This doesn't happen with lists:

In [102]:
print(count,type(count),id(count))
count[-1] = 21
print(count,type(count),id(count))

[10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 21] <class 'list'> 4532538816
[10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 21] <class 'list'> 4532538816


In [60]:
count_t = count_t

4392395328


### Concept reminder:

1. Functions:
    - are used for calculations you want to do repeatedly. Instead of coding the same thing again and again, you just call the function and you get the result for each case you want.
    - Functions need a good docstring!
    - The main body of your code and the function can have different names for the same quantity. The name should be consistent in the same body though!
    - When your function gives a result you should calculate these numbers some other way to check that they are correct
    


2. Lists:
    - defined using: [ ]
    - slicing
    - mutable
    
    
    

3. Tuples:
    - defined using ( )
    - slicing
    - immutable



### Practice: 
Create a function `circuit_resistance` that takes the measured voltage across a circuit element and the current through that circuit element and returns the circuit element's resistance. Following Ohm's law:

$R = \frac{V}{I}$

Remember to use a good, appropriate docstring! 

- Call circuit_resistance for I = 4A and V = 0.1, 2, and 40 V using a numpy array.  

- Call circuit_resistance for V = 100 V and I = 0.1, 4, and 100 A using a numpy array.

- Call circuit_resistance using the V and I arrays but only print the resistance corresponding to the second element of both V and I.

- Print your docstring to the screen!


## More with Numpy
In the 2nd part of this book, we will study the numerical methods by using Python. We will use array/matrix a lot later in the book. Therefore, here we are going to introduce the most common way to handle arrays in Python using the [Numpy module](http://www.numpy.org). Numpy is probably the most fundamental numerical computing module in Python. 

NumPy is important in scientific computing, it is coded both in Python and C (for speed). On its website, a few important features for Numpy is listed:

* a powerful N-dimensional array object
* sophisticated (broadcasting) functions
* tools for integrating C/C++ and Fortran code
* useful linear algebra, Fourier transform, and random number capabilities

**Scipy** is the complimentary package which we will also use quite a lot. As a rule of thumb, if something is covered in a general textbook on numerical computing, it’s probably implemented in SciPy.

As always, let's start with some imports:

In [21]:
import numpy as np
import matplotlib.pyplot as plt #We will also be making some plots to demonstrate numpy functions.

In [2]:
import matplotlib.pyplot  as plt   
## remember that if you knew --for some very weird case-- that you only need 1 or 2 packages you could just import
## those with: from matplotlib.pyplot import plot or (plot, xlabel, ylabel...)

## Array Creation

**Recall** We've already learned a few ways to create arrays. Let's look at some examples:


In [24]:
x_1d = np.arange( 3, 50.1, 0.1 ) #Creates a 1D array starting on 3 and ending on 50 with a step of 0.1.
y_1d = np.linspace(0,10,num = 471) #Creates a 1D array with 471 evenly spaced elements from 0 to 10.
z_1d = np.array([1,2,3]) #Creates an array from a list
z_2d = np.array([[1,2,3],[4,5,6],[7,8,9]]) #Creates a 2D array from a list of lists.

In [29]:
print(x_1d[0:5],'... \n',y_1d[0:5],'...\n',z_1d,'\n \n',z_2d)

[3.  3.1 3.2 3.3 3.4] ... 
 [0.         0.0212766  0.04255319 0.06382979 0.08510638] ...
 [1 2 3] 
 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


### Array are better equiped for math than lists

**TRY IT!** Try multiplying our array, z_1d and a list version by the scalar 10. Does 10 distribute to all elements? 

In [31]:
zlist = list(z_1d)

print(z_1d*10)
print(zlist*10)

[10 20 30]
[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]


It looks like the list creates 10 copies of the original list. This may be good for some programming tasks but in general the numpy array behaves much more like we would expect from math.

### Lists are not arrays. 
To do numerical computations with their elements we need to call them one by one. 
You need a *for loop* or this: [i*10 for i in x_list] and you will get the same results as with x_numpy * 10. 
We will study *for loops* in more detail next week.


In [41]:
z10a = []
for i in range( len( zlist ) ):
    z10a.append( zlist[i] * 10 )

print(z10a)
#or

z10b = []
for num in zlist: z10b.append(num*10)

print(z10b)

[10, 20, 30]
[10, 20, 30]


In [42]:
#or even simpler: 
[ i*10 for i in zlist ]   # ---> "list comprehension" we will get to this later in the course.

[10, 20, 30]